//
//  TextAIModel.swift
//  broche
//
//  Created by Zhu Zhanyan on 2026-07-23.
//

/// Text Generation AI models aka Language Models (LLMs)
/// Options that control text generation.
struct TextAIOptions {
    /// Controls randomness during sampling.
    var temperature: Float = 1.0
    /// Controls the cumulative probability threshold for top-p sampling. Only used if temperature > 0.
    var topP: Float = 1.0
    /// Controls the number of highest probability tokens to keep for top-k sampling. Only used if temperature > 0.
    var topK: Int = 40
    /// Sets the generation seed for reproducibility. If set to 0, a random seed will be used.
    var seed: Int = 42
}

/// Metrics collected during text generation.
struct TextAIMetrics {
    /// The number of tokens in the prompt.
    var nPromptTokens: Int
    /// The number of tokens generated by the model.
    var nGenerationTokens: Int
}

/// The output of a text generation model
enum TextAIOutput: Error {
    /// Indicates that a chunk of text has been generated.
    case chunk(text: String)
    /// Indicates that the generation is complete and provides metrics.
    case complete(metrics: TextAIMetrics)
}

protocol TextAIModel: AIModel {
    /// Generates text for the given prompt.
    ///
    /// - Parameters:
    ///   - prompt: The input prompt to generate a completion for.
    ///   - options: Configuration controlling text generation.
    /// - Returns: An asynchronous stream of generated text chunks.
    /// - Throws: An error if generation fails or the model has not been loaded.
    func generate(
        prompt: String,
        options: TextAIOptions
    ) -> AsyncThrowingStream<TextAIOutput, Error>
}
