//
//  TextAIModel.swift
//  broche
//
//  Created by Zhu Zhanyan on 2026-07-23.
//
import Foundation

/// Text Generation AI models aka Language Models (LLMs)
/// Options that control text generation.
struct TextAIOptions {
    /// Controls randomness during sampling.
    var temperature: Float = 1.0
    /// Controls the cumulative probability threshold for top-p sampling. Only used if temperature > 0.
    var topP: Float = 1.0
    /// Controls the number of highest probability tokens to keep for top-k sampling. Only used if temperature > 0.
    var topK: Int = 40
    /// Sets the generation seed for reproducibility. If set to 0, a random seed will be used.
    var seed: Int = 42
}

/// Metrics collected during text generation.
struct TextAIMetrics {
    /// The number of tokens in the prompt.
    var nPromptTokens: Int = 0
    /// The number of tokens generated by the model.
    var nGenerationTokens: Int = 0
}

/// The output of a text generation model
enum TextAIOutput: Error {
    /// Indicates that a chunk of text has been generated.
    case chunk(text: String)
    /// Indicates that the generation is complete and provides metrics.
    case complete(metrics: TextAIMetrics)
}

protocol TextAIModel: AIModel {
    /// Generates text for the given prompt.
    ///
    /// - Parameters:
    ///   - prompt: The input prompt to generate a completion for.
    ///   - options: Configuration controlling text generation.
    /// - Returns: An asynchronous stream of generated text chunks.
    /// - Throws: An error if generation fails or the model has not been loaded.
    func generate(
        prompt: String,
        options: TextAIOptions
    ) -> AsyncThrowingStream<TextAIOutput, Error>
}

/// Benchmarks a ``TextAIModel`` by generating text with a fixed prompt
/// and collecting model-reported metrics.
///
/// Conforms to ``AIBenchmark``. Use ``evaluate(_:)`` to load the model,
/// run generation, and collect timings and memory usage.
class TextAIBenchmark<Model: TextAIModel>: AIBenchmark {
    /// Text generated by the model during the benchmark.
    var response: String = ""

    func generate(_ model: Model) async throws -> AIMetrics {
        response = ""
        let stream = model.generate(
            prompt: "Explain how to paint a watercolor, step by step",
            options: TextAIOptions(temperature: 1.0, topP: 1.0, topK: 40, seed: 42)
        )
        for try await output in stream {
            switch output {
            case .chunk(let text):
                response += text
            case .complete(let metrics):
                return .text(metrics)
            }
        }
        throw AIBenchmarkError.NoMetricsReported
    }
}
