//
//  VisualAIModel.swift
//  broche
//
//  Created by Zhu Zhanyan on 2026-07-28
//

import UIKit

/// Visual Language Generation AI models aka (VLMs)
/// Options that control visual text generation.
typealias VisualAIOptions = TextAIOptions

/// Metrics collected during visual text generation.
typealias VisualAIMetrics = TextAIMetrics

/// Errors that can occur during visual text generation.
enum VisualAIError: Error, LocalizedError {
    case modelNotLoaded
    case imageDecodingFailed
    var errorDescription: String? {
        switch self {
        case .modelNotLoaded:
            return "Model has not been loaded. Call load(:) first."
        case .imageDecodingFailed:
            return "Failed to decode the provided image data."
        }
    }
}

/// The output of a visual text generation model
typealias VisualAIOutput = TextAIOutput

protocol VisualAIModel: AIModel, Sendable {
    /// Generates text for the given prompt.
    ///
    /// - Parameters:
    ///   - prompt: The input prompt to generate a completion for.
    ///   - images: PNG encoded images as data to be used as visual context for generation.
    ///   - options: Configuration controlling text generation.
    /// - Returns: An asynchronous stream of generated text chunks.
    /// - Throws: An error if generation fails or the model has not been loaded.
    func generate(
        prompt: String,
        images: [Data],
        options: VisualAIOptions
    ) -> AsyncThrowingStream<VisualAIOutput, Error>
}

/// Benchmarks a ``VisualAIModel`` by generating text with a fixed prompt
/// and collecting model-reported metrics.
///
/// Conforms to ``AIBenchmark``. Use ``evaluate(_:)`` to load the model,
/// run generation, and collect timings and memory usage.
class VisualAIBenchmark<Model: VisualAIModel>: AIBenchmark {
    /// Text generated by the model during the benchmark.
    var response: String = ""

    func generate(_ model: Model) async throws -> AIMetrics {
        response = ""
        let stream = model.generate(
            prompt: "Describe what you see in this image in detail",
            images: [TestFixtures.appleSketchData],
            options: VisualAIOptions(temperature: 1.0, topP: 1.0, topK: 40, seed: 42)
        )
        for try await output in stream {
            switch output {
            case .chunk(let text):
                response += text
            case .call(let call):
                print("Ignored tool call in benchmark: \(call)")
            case .complete(let metrics):
                return .visual(metrics)
            }
        }
        throw AIBenchmarkError.NoMetricsReported
    }
}
