//
//  AIBenchmark.swift
//  broche
//
//  Created by Zhu Zhanyan on 2026-07-22
//

import Foundation

/// The result of benchmarking a ``TextAIModel``.
///
/// Contains wall-clock timings, model-reported metrics, memory usage,
/// and the generated response text.
struct AIBenchmarkResult {
    /// The identifier of the model that was benchmarked.
    var modelID: String
    /// Wall-clock time taken to load the model, in seconds.
    var loadTimeSecs: Double
    /// Wall-clock time from the start of generation to the final token, in seconds.
    var wallClockGenTimeSecs: Double
    /// The full text generated by the model.
    var response: String
    /// Model-reported token counts, or `nil` if the model did not emit metrics.
    var metrics: TextAIMetrics?
    /// Peak memory increase during the benchmark in megabytes, or `nil` if unavailable.
    var memoryUsedMB: Float?
}

extension AIBenchmarkResult: CustomStringConvertible {
    var description: String {
        var lines: [String] = []
        lines.append("--- Benchmark: \(modelID) ---")
        lines.append("Load time:       \(String(format: "%.2f", loadTimeSecs))s")
        lines.append("Latency:         \(String(format: "%.2f", wallClockGenTimeSecs))s")
        if let metrics {
            lines.append("Prompt tokens:   \(metrics.nPromptTokens)")
            lines.append("Generated tokens:\(metrics.nGenerationTokens)")
            let tps =
                wallClockGenTimeSecs > 0
                    ? Double(metrics.nGenerationTokens) / wallClockGenTimeSecs : 0
            lines.append("TPS:             \(String(format: "%.2f", tps))")
        }
        if let memoryUsedMB {
            lines.append("Memory Used:     \(String(format: "%.1f", memoryUsedMB)) MB")
        }
        lines.append("Response:        \(response)")
        lines.append("---------------------------")
        return lines.joined(separator: "\n")
    }
}

/// Benchmarks a ``TextAIModel`` by loading it, generating text, and collecting performance data.
///
/// - Parameters:
///   - model: Any conformer to ``TextAIModel`` (e.g. ``MLXTextAIModel``).
/// - Returns: A ``AIBenchmarkResult`` containing timings, metrics, memory usage, and the response.
/// - Throws: Any error from model loading or text generation.
func benchmarkAI(_ model: some TextAIModel) async throws -> AIBenchmarkResult {
    let memBefore = memoryFootprint()

    let loadStart = CFAbsoluteTimeGetCurrent()
    try await model.load()
    let loadTime = CFAbsoluteTimeGetCurrent() - loadStart

    let stream = try await model.generate(
        prompt: "Explain how to paint a watercolor, step by step",
        options: TextAIOptions(temperature: 1.0, topP: 1.0, topK: 40, seed: 42)
    )

    var response = ""
    var metrics: TextAIMetrics?
    let genStart = CFAbsoluteTimeGetCurrent()
    for try await output in stream {
        switch output {
        case let .chunk(text):
            response += text
        case let .complete(m):
            metrics = m
        }
    }
    let genTime = CFAbsoluteTimeGetCurrent() - genStart

    let memAfter = memoryFootprint()
    let memoryUsedMB = memAfter.map { ($0 - memBefore!) / 1024 / 1024 }

    return AIBenchmarkResult(
        modelID: model.modelID,
        loadTimeSecs: loadTime,
        wallClockGenTimeSecs: genTime,
        response: response,
        metrics: metrics,
        memoryUsedMB: memoryUsedMB
    )
}

/// Returns the current process's physical memory footprint in bytes, or `nil` if unavailable.
private func memoryFootprint() -> Float? {
    let TASK_VM_INFO_COUNT = mach_msg_type_number_t(
        MemoryLayout<task_vm_info_data_t>.size / MemoryLayout<integer_t>.size
    )
    let TASK_VM_INFO_REV1_COUNT = mach_msg_type_number_t(
        MemoryLayout.offset(of: \task_vm_info_data_t.min_address)!
            / MemoryLayout<integer_t>.size
    )
    var info = task_vm_info_data_t()
    var count = TASK_VM_INFO_COUNT
    let kr = withUnsafeMutablePointer(to: &info) { infoPtr in
        infoPtr.withMemoryRebound(to: integer_t.self, capacity: Int(count)) { intPtr in
            task_info(mach_task_self_, task_flavor_t(TASK_VM_INFO), intPtr, &count)
        }
    }
    guard
        kr == KERN_SUCCESS,
        count >= TASK_VM_INFO_REV1_COUNT
    else { return nil }

    return Float(info.phys_footprint)
}
