//
//  AIModel.swift
//  broche
//
//  Created by Zhu Zhanyan on 2026-07-20.
//

/// A minimal interface for loading a AI model
protocol AIModel {
    /// Loads the model weights of a model with a specific model ID on HuggingFace.
    ///
    /// - Parameter modelID : The ID of the model to load.
    /// - Throws: An error if the model cannot be found, loaded, or initialized.
    func load(modelID: String) async throws
}

/// Text Generation AI models aka Language Models (LLMs)
/// Options that control text generation.
struct TextAIOptions {
    /// The maximum number of tokens to generate.
    var maxTokens: Int = 256

    /// Controls randomness during sampling.
    var temperature: Float = 1.0
}

/// Metrics collected during text generation.
struct TextAIMetrics {
    // The number of tokens in the prompt.
    var nPromptTokens: Int
    // The number of tokens generated by the model.
    var nGenerationTokens: Int
}

/// The output of a text generation model
enum TextAIOutput:Error {
    /// Indicates that a chunk of text has been generated.
    case chunk(text: String)
    // Indicates that the generation is complete and provides metrics.
    case complete(metrics: TextAIMetrics)
}

protocol TextAIModel: AIModel {
    /// Generates text for the given prompt.
    ///
    /// - Parameters:
    ///   - prompt: The input prompt to generate a completion for.
    ///   - options: Configuration controlling text generation.
    /// - Returns: An asynchronous stream of generated text chunks.
    /// - Throws: An error if generation fails or the model has not been loaded.
    func generate(
        prompt: String,
        options: TextAIOptions
    ) async throws -> AsyncThrowingStream<TextAIOutput, Error>
}
